services:
  backend:
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - NODE_ENV=development
    build:
      context: . # <--- Look at the root folder
      dockerfile: backend/Dockerfile # <--- Path to the specific file
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    build:
      context: . # <--- Look at the root folder
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
