name: CI Gatekeeper

on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Install pnpm, but tell it NOT to run install automatically
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11
          run_install: false

      # Setup Node with wildcard cache path
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      # Manual targeted installation
      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --prefix backend
          pnpm install --frozen-lockfile --prefix frontend

      - name: Build Next.js Backend
        run: |
          if git diff --quiet HEAD^ HEAD ./backend; then
            echo "No changes in backend. Skipping..."
          else
            pnpm run build --prefix backend
          fi

      - name: Build Vite Frontend
        run: |
          if git diff --quiet HEAD^ HEAD ./frontend; then
            echo "No changes in frontend. Skipping..."
          else
            pnpm run build --prefix frontend
          fi
