name: CI Gatekeeper

on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "extension/**"
      - ".github/workflows/ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      # Setup Node and point it to the pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Recommended LTS for 2026 stability
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile # Correct command for CI

      - name: Build Next.js Backend
        run: |
          if git diff --quiet HEAD^ HEAD ./backend; then
            echo "No changes in backend. Skipping..."
          else
            pnpm run build --prefix backend
          fi

      - name: Build Chrome Extension
        run: |
          if git diff --quiet HEAD^ HEAD ./extension; then
            echo "No changes in extension. Skipping..."
          else
            pnpm run build --prefix extension
          fi
